# Generated by Django 4.2 on 2026-02-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('college', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('IS', 'Information Science'), ('EC', 'Electronics & Communication'), ('EE', 'Electrical & Electronics'), ('ME', 'Mechanical'), ('CV', 'Civil')], max_length=50)),
                ('sem', models.IntegerField()),
                ('course', models.CharField(choices=[('JFSWD', 'Java Full Stack Web Development'), ('PFSWD', 'Python Full Stack Web Development'), ('MERN', 'MERN Stack Web Development'), ('MEAN', 'MEAN Stack Web Development')], max_length=50)),
            ],
        ),
    ]
